### PR TITLE
Rebuild with leptonica 1.80

### PR DESCRIPTION
**Pull request by izahn**
…nda-forge-pinning 2021.05.21.13.51.08

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR just jumps the build number and rerender in order to get a build with leptonica 1.80.

### CODE REVIEW

**Comment by izahn** [comment]
I had hoped this update would be uneventful, but I'm having trouble getting the windows build to work with leptonica 1.80. The errors look like this:

```
MANIFESTFILE:bin\tesseract41.dll.manifest" failed (exit code 1120) with the following output:
2021-05-23T15:55:40.3446181Z    Creating library tesseract41.lib and object tesseract41.exp
2021-05-23T15:55:40.3447563Z leptonica-1.80.0.lib(tiffio.c.obj) : error LNK2019: unresolved external symbol TIFFCleanup referenced in function findTiffCompression
2021-05-23T15:55:40.3448773Z leptonica-1.80.0.lib(tiffio.c.obj) : error LNK2019: unresolved external symbol TIFFClose referenced in function extractG4DataFromFile
2021-05-23T15:55:40.3450304Z leptonica-1.80.0.lib(tiffio.c.obj) : error LNK2019: unresolved external symbol TIFFGetField referenced in function "int __cdecl getTiffStreamResolution(struct tiff *,int *,int *)" (?getTiffStreamResolution@@YAHPEAUtiff@@PEAH1@Z)
```

I'm probably missing something obvious but I don't see what.

**Comment by izahn** [comment]
@conda-forge-admin please restart ci

**Comment by izahn** [comment]
This PR is ready for review! It rebuilds tesseract with leptionica 1.80 on all platforms except windows. I've concluded that there is a problem with the windows build of leptionica 1.80 and have stuck with leptonica 1.78 on windows for now; see https://github.com/conda-forge/tesseract-feedstock/pull/31

**Comment by xylar** [comment]
@izahn, do you want to add yourself as a maintainer or do you prefer not to?

**Comment by izahn** [comment]
> @izahn, do you want to add yourself as a maintainer or do you prefer not to?

Sure, happy to!

**Comment by xylar** [comment]
@izahn, thanks so much for this work!
